name: "Gomu Gomu no Gatling"
description: "Run Gomu Gomu no Gatling to benchmark Starknet Sequencers"
branding:
  icon: "activity-circle"
  color: "orange"
inputs:
  config_path:
    description: "Path to the configuration file"
    required: true
runs:
  using: "composite"
  steps:
    - run: wget https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/releases/download/v0.0.2-1-alpha/x86_64-unknown-linux-gnu-gatling -O gatling
      shell: bash
    - run: chmod +x gatling
      shell: bash
    - run: RUST_LOG=info ./gatling shoot -c ${{ inputs.config_path }}
      shell: bash
