---
name: Workflow - Daily Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # Known issue on exceeding secondary rate limits
  # https://github.com/dessant/lock-threads/issues/48
  # lock_closed:
  #   name: Lock closed issues/PRs
  #   uses: ./.github/workflows/lock-closed.yml

  security_audit:
    name: Security audit
    uses: ./.github/workflows/security-audit.yml
