---
name: Task - Linters

on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run prettier
        run: |-
          npx prettier --check .
