---
name: Workflow - Push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_build
